### ISSUE TITLE
Migrations - Users

### ISSUE THREAD

**Issue by totarochristian** [MarcoBione/hungry-backoffice#1]
Modificare la migrazione di Users aggiungendo i nuovi campi.

Riferimento: Schema ER versione 2

**Comment by MarcoBione** [comment]
Aggiunto il campo "partita iva" in fase di registrazione, salvando il dato nella tabella "Users" come da richiesta.
modificati i file:
- register.blade -> aggiunto campo testuale per l'aggiunta del codice
- registered user controller aggiungendo :

sotto validate:

`$request->validate([
'partitaiva' => ['required', 'string', 'max:11'],
]);`

sotto user:

`$user = User::create([
'partitaiva' => $request->partitaiva,
]);`

- profile update request -> aggiunto campo :
      sotto public function rules():

      `'partitaiva' => ['string', 'max:11' ],`
