### ISSUE TITLE
Gestire Registrazione

### ISSUE THREAD

**Issue by totarochristian** [MarcoBione/hungry-backoffice#11]
Gestire la parte di registrazione degli utenti, aggiungendo i nuovi campi dell'utente ed eventualmente i dati di un nuovo ristorante.

**Comment by totarochristian** [comment]
Da controllare perchè non si legge la partita iva (vat_number)

**Comment by MarcoBione** [comment]
Prendo in carico l'Issue!

branch,

git fetch origin
git checkout 11-gestire-registrazione

**Comment by MarcoBione** [comment]
risolto l'issue sulla registrazione del vat_number da parte della tabella "Users"

modificato il model di Users cambiando nel campo dei fillable la parola "partitaiva" con "vat_number"
