### ISSUE TITLE
CRUDS - Caterers

### ISSUE THREAD

**Issue by totarochristian** [MarcoBione/hungry-backoffice#13]
Gestire le CRUDS dei Caterers.
In particolare:
- Index
- Show
- Create
Solo dopo, se avanza tempo:
- Edit
- Delete

**Comment by totarochristian** [comment]
Mi raccomando, compilare anche le request per la validazione dei dati per la creazione e la modifica.

**Comment by totarochristian** [comment]
Stato delle CRUDS:
- la visualizzazione dei caterers funziona correttamente
- durante la modifica di un caterer anche se i dati vengono aggiornati correttamente, all'apertura della pagina non vengono visualizzate le categories selezionate
- se provo ad aggiungere un nuovo caterer, va in errore "compact(): Undefined variable $dishes"
- l'eliminazione di un caterer funziona ma senza mostrare un messaggio d'errore

**Comment by AndreaCollura** [comment]
- da sistemare il menù nella pagina di dettaglio del ristorante

**Comment by totarochristian** [comment]
{
   tipologies: [
    {
      id: 1,
      name: 'Primi',
      description: 'Questa categoria del menù contiene tutti i piatti di pasta',
      class: 'bg-blue text-light',
      dishes: [
        {
          id: 1,
          name: 'Pasta allo scoglio',
          description: 'La pasta allo scoglio del nostro ristorante contiene anche i gamberetti',
          price: 12.5,
          visible: true,
          image: 'http://pippopluto.paperino.com/blablascoglio.jpg'
        },
        {
          id: 2,
          name: 'Penne all'arrabbiata',
          description: 'Le penne all'arrabbiata normalmente le facciamo scotte',
          price: 5.6,
          visible: true,
          image: 'http://pippopluto.paperino.com/fragolinastellinaarrabbiata.jpg'
        }
      ]
    },
    {
      id: 2,
      name: 'Secondi di Terra',
      description: 'Questa categoria del menù contiene tutti i secondi di terra',
      class: 'bg-green text-light',
      dishes: [
        {
          id: 3,
          name: 'Cotoletta',
          description: 'La cotoletta è molto buona',
          price: 6.7,
          visible: true,
          image: 'http://pippopluto.paperino.com/cotolettapiccolina.jpg'
        },
        {
          id: 4,
          name: 'Carote e piselli',
          description: 'Le carote e i piselli raccolti nel nostro orticello della fantasia',
          price: 2.3,
          visible: true,
          image: 'http://pippopluto.paperino.com/chebuono.jpg'
        }
      ]
    },
    {
      id: 3,
      name: 'Prodotti da noi',
      description: 'Questa categoria del menù contiene tutti i prodotti caserecci',
      class: 'bg-yellow text-dark',
      dishes: [
        {
          id: 2,
          name: 'Penne all'arrabbiata',
          description: 'Le penne all'arrabbiata normalmente le facciamo scotte',
          price: 5.6,
          visible: true,
          image: 'http://pippopluto.paperino.com/fragolinastellinaarrabbiata.jpg'
        },
        {
          id: 4,
          name: 'Carote e piselli',
          description: 'Le carote e i piselli raccolti nel nostro orticello della fantasia',
          price: 2.3,
          visible: true,
          image: 'http://pippopluto.paperino.com/chebuono.jpg'
        }
      ]
    }
  ]
}

**Comment by totarochristian** [comment]
il menù è stato realizzato da @marikadiblasio utilizzando gli accordion
