### ISSUE TITLE
CRUDS - Categories

### ISSUE THREAD

**Issue by totarochristian** [MarcoBione/hungry-backoffice#14]
Gestire le CRUDS delle Categories.
In particolare:
- Index
- Show
- Create
Solo dopo, se avanza tempo:
- Edit
- Delete

**Comment by totarochristian** [comment]
Stato delle CRUDS:
- le categorie vengono visualizzate ma non c'è la paginazione dei dati e le immagini (anche se al momento usiamo link) non vengono visualizzate
- il dettaglio di una categoria viene visualizzato ma ci sono dei bug grafici: l'immagine viene schiacciata a destra
- la modifica delle categorie mostra qualche bug: quando apro la modifica il campo della descrizione risulta vuoto anche se in realtà c'è del testo
- la creazione di una nuova categoria funziona
- l'eliminazione di una categoria (con tanto di modale) funziona correttamente

**Comment by AndreaCollura** [comment]
- terminate CRUDS
- sistemati bug grafici
- eseguiti test di funzionamento
- impostata paginazione da 10 a 3
