### ISSUE TITLE
CRUDS - Dishes

### ISSUE THREAD

**Issue by totarochristian** [MarcoBione/hungry-backoffice#15]
Gestire le CRUDS dei Dishes.
In particolare:
- Index
- Show
- Create
Solo dopo, se avanza tempo:
- Edit
- Delete

**Comment by totarochristian** [comment]
Mi raccomando, compilare anche le request per la validazione dei dati per la creazione e la modifica.

**Comment by MarcoBione** [comment]
Per Marika:

git fetch origin
git checkout 15-cruds-dishes

**Comment by totarochristian** [comment]
Stato delle CRUDS:
- manca il link alla pagina index dei piatti
- arrivando all'index dei piatti manualmente manca uno stile grafico ma viene visualizzata una lista testuale con tutti i nomi dei piatti
- non ho potuto testare le altre cruds perchè non sono raggiungibili

**Comment by AndreaCollura** [comment]
- trovato bug su create dish

**Comment by totarochristian** [comment]
Fixato il bug sulla creazione del piatto
