### ISSUE TITLE
CRUDS - Orders

### ISSUE THREAD

**Issue by totarochristian** [MarcoBione/hungry-backoffice#16]
Gestire le CRUDS degli Orders.
In particolare:
- Index
- Show
- Create
Solo dopo, se avanza tempo:
- Edit
- Delete

**Comment by totarochristian** [comment]
Mi raccomando, compilare anche le request per la validazione dei dati per la creazione e la modifica.

**Comment by totarochristian** [comment]
Stato delle CRUDS:
- l'index degli ordini viene visualizzato e ha i pulsanti per dirigersi verso il dettaglio, la modifica e l'eliminazione di ogni ordine
- la show degli ordini funziona
- bisogna realizzare l'edit e la delete

**Comment by totarochristian** [comment]
Aggiornamento sullo stato delle CRUDS:
- gestita eliminazione degli ordini dall'index degli ordini
- gestita modifica degli ordini dall'index degli ordini: nella pagina di modifica i campi editabili sono lo status, il total_price e l'address.
- la crud di creazione di un nuovo ordine non è stata realizzata perchè non ha senso creare un nuovo ordine tramite questa sezione, qui vengono visualizzati gli ordini svolti dai clienti tramite le API che verranno realizzate e al limite vengono aggiornati indirizzi / stati / prezzi totali.

ATTENZIONE:
Ho perso un bel po' di tempo per capire perchè la pagina di edit quando inviavo la conferma dei dati non aggiornava i dati, la risposta sta nell'update request. In sostanza se si hanno regole su campi non presenti, queste regole vengono verificate ugualmente quindi se si mette un campo non esistente come required, il form non verrà mai inviato.

**Comment by AndreaCollura** [comment]
- da realizzare la visualizzazione degli ordini legati solo al proprio ristorante
